name: Request a new company
description: Make a request for a new company to be added to the Brændstofpriser integration
labels: ["companies_new"]
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for requesting a new company to be added to the integration
  - type: input
    id: company_name
    validations:
      required: true
    attributes:
      label: Name of the company?
      placeholder: Example Company
  - type: input
    id: url
    validations:
      required: true
    attributes:
      label: URL to the page displaying prices?
      placeholder: https://www.example.com/fuel-prices
      description: >
        Publicly available URL to the page displaying fuel prices for the company you are requesting.
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, regarding this request, please use the field below.
